name: Build
concurrency: build

on:
  push:
  pull_request:
    branches:
      - 'main'

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - uses: haskell/actions/setup@ce6c3a6f8cbe3bd6ce51b635b3f32ee792f22f91 # v2.4.7
        with:
          enable-stack: true
      
      - uses: actions/cache@2cdf405574d6ef1f33a1d12acccd3ae82f47b3f2 # v4.1.0
        with:
          path: ~/.stack
          key: stack-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('package.yaml', 'stack.yaml') }}
          restore-keys: stack-

      - id: cache-build-objects
        uses: actions/cache@2cdf405574d6ef1f33a1d12acccd3ae82f47b3f2 # v4.1.0
        with:
          path: .stack-work
          key: build-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('app/**', 'src/**', 'test/**') }}
          restore-keys: build-

      - run: stack build --test
