name: Build
concurrency: build

on:
  push:
  pull_request:
    branches:
      - 'main'

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: haskell/actions/setup@ce6c3a6f8cbe3bd6ce51b635b3f32ee792f22f91 # v2.4.7
        with:
          enable-stack: true
      
      - uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: ~/.stack
          key: stack-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('package.yaml', 'stack.yaml') }}
          restore-keys: stack-

      - id: cache-build-objects
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: .stack-work
          key: build-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('app/**', 'src/**', 'test/**') }}
          restore-keys: build-

      - run: stack build --test
