name: Build
concurrency: build

on:
  push:
  pull_request:
    branches:
      - 'main'

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - uses: haskell/actions/setup@9c0664b388ccf0c42d216435e3b42648d4a73b57 # v2.4.0
        with:
          enable-stack: true
      
      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: ~/.stack
          key: stack-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('package.yaml', 'stack.yaml') }}
          restore-keys: stack-

      - id: cache-build-objects
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: .stack-work
          key: build-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('app/**', 'src/**', 'test/**') }}
          restore-keys: build-

      - run: stack build --test
