name: HLint

on:
  push:
  schedule:
    - cron: '9 4 * * 4'

permissions: read-all

jobs:
  hlint:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: haskell-actions/hlint-scan@a99e50c562954d0c73211df1d7dabd33128b1098 # v1.0.0
