name: Lint

on:
  push:
    paths:
      - '**.hs'

permissions: read-all

jobs:
  hlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - uses: haskell/actions/hlint-setup@5ff2575cfa27ef8693b7252e0ed1cb0ad87af57e # v2.3.7
      - uses: haskell/actions/hlint-run@5ff2575cfa27ef8693b7252e0ed1cb0ad87af57e # v2.3.7
        with:
          path: '["app/", "src/", "test/"]'
          fail-on: warning
